_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
add_data_extension:
    value:
        - bev_visibility.png
cav_lidar_range:
    value:
        - -51.2
        - -51.2
        - -3
        - 51.2
        - 51.2
        - 1
comm_range:
    value: 70
fusion:
    value:
        args:
            data_aug_conf: None
            grid_conf: None
            proj_first: false
        core_method: intermediateheter
        dataset: opv2v
heter:
    value:
        assignment_path: opencood/modality_assign/opv2v_4modality.json
        ego_modality: m2
        mapping_dict:
            m1: m2
            m2: m2
            m3: m2
            m4: m2
        modality_setting:
            m2:
                core_method: lift_splat_shoot
                data_aug_conf:
                    H: 600
                    Ncams: 4
                    W: 800
                    bot_pct_lim:
                        - 0
                        - 0.05
                    cams:
                        - camera0
                        - camera1
                        - camera2
                        - camera3
                    final_dim:
                        - 384
                        - 512
                    rand_flip: false
                    resize_lim:
                        - 0.65
                        - 0.7
                    rot_lim:
                        - -3.6
                        - 3.6
                grid_conf:
                    ddiscr:
                        - 2
                        - 50
                        - 48
                    mode: LID
                    xbound:
                        - -51.2
                        - 51.2
                        - 0.4
                    ybound:
                        - -51.2
                        - 51.2
                        - 0.4
                    zbound:
                        - -10
                        - 10
                        - 20
                sensor_type: camera
input_source:
    value:
        - camera
        - depth
label_type:
    value: camera
loss:
    value:
        args:
            cls:
                alpha: 0.25
                gamma: 2
                type: SigmoidFocalLoss
                weight: 2
            depth:
                weight: 1
            dir:
                args:
                    anchor_yaw:
                        - 0
                        - 90
                    dir_offset: 0.7853
                    num_bins: 2
                type: WeightedSoftmaxClassificationLoss
                weight: 0.2
            generate_weight: 1
            pos_cls_weight: 2
            reg:
                codewise: true
                sigma: 3
                type: WeightedSmoothL1Loss
                weight: 2
        core_method: point_pillar_diffcomm_loss
lr_scheduler:
    value:
        core_method: multistep
        gamma: 0.1
        step_size:
            - 3
model:
    value:
        args:
            anchor_number: 2
            att:
                feat_dim: 128
            diffcomm:
                diffusion:
                    beta_end: 0.02
                    beta_schedule: linear
                    beta_start: 0.0005
                    num_diffusion_timesteps: 3
                model:
                    attn_resolutions:
                        - 16
                    ch: 8
                    ch_mult:
                        - 1
                        - 1
                    dropout: 0
                    embed_dim: 130
                    in_channels: 128
                    num_res_blocks: 2
                    out_ch: 128
                    resamp_with_conv: true
            dir_args:
                anchor_yaw:
                    - 0
                    - 90
                dir_offset: 0.7853
                num_bins: 2
            ego_modality: m2
            fusion_method: att
            in_head: 128
            lidar_range:
                - -51.2
                - -51.2
                - -3
                - 51.2
                - 51.2
                - 1
            m2:
                aligner_args:
                    core_method: identity
                backbone_args:
                    inplanes: 128
                    layer_nums:
                        - 3
                        - 5
                        - 8
                    layer_strides:
                        - 2
                        - 2
                        - 2
                    num_filters:
                        - 64
                        - 128
                        - 256
                    num_upsample_filter:
                        - 128
                        - 128
                        - 128
                    upsample_strides:
                        - 1
                        - 2
                        - 4
                camera_mask_args:
                    cav_lidar_range:
                        - -51.2
                        - -51.2
                        - -3
                        - 51.2
                        - 51.2
                        - 1
                    grid_conf:
                        ddiscr:
                            - 2
                            - 50
                            - 48
                        mode: LID
                        xbound:
                            - -51.2
                            - 51.2
                            - 0.4
                        ybound:
                            - -51.2
                            - 51.2
                            - 0.4
                        zbound:
                            - -10
                            - 10
                            - 20
                core_method: lift_splat_shoot
                encoder_args:
                    anchor_number: 2
                    camera_encoder: EfficientNet
                    data_aug_conf:
                        H: 600
                        Ncams: 4
                        W: 800
                        bot_pct_lim:
                            - 0
                            - 0.05
                        cams:
                            - camera0
                            - camera1
                            - camera2
                            - camera3
                        final_dim:
                            - 384
                            - 512
                        rand_flip: false
                        resize_lim:
                            - 0.65
                            - 0.7
                        rot_lim:
                            - -3.6
                            - 3.6
                    depth_supervision: true
                    grid_conf:
                        ddiscr:
                            - 2
                            - 50
                            - 48
                        mode: LID
                        xbound:
                            - -51.2
                            - 51.2
                            - 0.4
                        ybound:
                            - -51.2
                            - 51.2
                            - 0.4
                        zbound:
                            - -10
                            - 10
                            - 20
                    img_downsample: 8
                    img_features: 128
                    use_depth_gt: false
                sensor_type: camera
                shrink_header:
                    dim:
                        - 128
                    input_dim: 384
                    kernal_size:
                        - 3
                    padding:
                        - 1
                    stride:
                        - 1
        core_method: heter_model_baseline_w_diffcomm
name:
    value: m2_diffcomm
optimizer:
    value:
        args:
            eps: 1e-10
            weight_decay: 0.0001
        core_method: Adam
        lr: 0.002
postprocess:
    value:
        anchor_args:
            D: 1
            H: 256
            W: 256
            cav_lidar_range:
                - -51.2
                - -51.2
                - -3
                - 51.2
                - 51.2
                - 1
            feature_stride: 2
            h: 1.56
            l: 3.9
            num: 2
            r:
                - 0
                - 90
            vd: 4
            vh: 0.4
            vw: 0.4
            w: 1.6
        core_method: VoxelPostprocessor
        dir_args:
            anchor_yaw:
                - 0
                - 90
            dir_offset: 0.7853
            num_bins: 2
        gt_range:
            - -51.2
            - -51.2
            - -3
            - 51.2
            - 51.2
            - 1
        max_num: 150
        nms_thresh: 0.15
        order: hwl
        target_args:
            neg_threshold: 0.45
            pos_threshold: 0.6
            score_threshold: 0.2
preprocess:
    value:
        args:
            max_points_per_voxel: 1
            max_voxel_test: 1
            max_voxel_train: 1
            voxel_size:
                - 0.4
                - 0.4
                - 4
        cav_lidar_range:
            - -51.2
            - -51.2
            - -3
            - 51.2
            - 51.2
            - 1
        core_method: SpVoxelPreprocessor
root_dir:
    value: /home/zjf/DATACENTER2/data/code/HEAL/opencood/dataset/OPV2V/train
test_dir:
    value: /home/zjf/DATACENTER2/data/code/HEAL/opencood/dataset/OPV2V/test
train_params:
    value:
        batch_size: 1
        epoches: 5
        eval_freq: 1
        max_cav: 5
        save_freq: 1
validate_dir:
    value: /home/zjf/DATACENTER2/data/code/HEAL/opencood/dataset/OPV2V/validate
verify_mode:
    value: true
yaml_parser:
    value: load_general_params
